name: "Jerry Hargrove - Cloud Diagrams & Notes"
twitter: awsgeek
markdown: kramdown
permalink: /posts/:title/index.html
url: https://www.awsgeek.com
analytics: UA-106486526-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed  
