name: "Jerry Hargrove - Cloud Diagrams & Notes"
twitter: awsgeek
markdown: kramdown
permalink: /posts/:title/index.html
url: https://www.awsgeek.com
analytics: UA-106486526-1
image : images/AWS-reInvent-2019-Keynote-Werner-Vogels_en.jpg

lsi: true

plugins:
  - jekyll-sitemap
  - jekyll-feed  
