version: 0.2
   
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install jekyll jekyll-sitemap jekyll-seo-tag jekyll-feed
      
  build:
    commands:
      - jekyll build

artifacts:
  base-directory: _site
  files:
    - '**/*'
